services:
  tracker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./tracker:/app/tracker
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    command: bash